language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxml2-utils
install: gem install jekyll
script:
  - jekyll build
  - jekyll doctor
  - find _site -name '*.html' -exec xmllint --noout {} \;
